apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app 
spec:
  replicas: 2 
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  selector:
    matchLabels:
      app: sa-web-app 
  template:
    metadata: 
      labels:
        app: sa-web-app 
    spec:
      containers:
      - image: bumblefeng/sentiment-analysis-web-app
        imagePullPolicy: Always 
        name: sa-web-app
        env:
        - name: SA_LOGIC_API_URL 
          value: "http://sa-logic"
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: sa-web-app-lb 
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080 
    nodePort: 30080
  selector:
    app: sa-web-app
  type: NodePort 

